import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
paddding.y = 10
decorations = "None"
opacity = 1
blur = true
option_as_alt = "Both"
startup_mode = "Maximized"
title = "Fanpero's Terminal"

[scrolling]
history = 10000
multiplier = 3

[font]
normal.family = "Fira Code nerd Font Mono"
size = 11

[cursor]
style.shape = "Bean"
style.blinking = "Never"

[selection]
save_to_clipboard = true
